### ISSUE TITLE
Mention which simulator should be run

### ISSUE THREAD

**Issue by mattrajca** [ashfurrow/xcode-hardware-performance#27]
The README should mention which simulator should be run (iPad Air, iPad Pro, iPad Air 2, etc) in case there are differences in launch times among them.

**Comment by ashfurrow** [comment]
Neat! This would have been a good idea when I created the repo, but after numerous community contributions, I'm not sure it's prudent or possible to add this constraint. 

Have you seen differences in launch times? I've always used iPad Air 2 just because that's the hardware we run the app on.

**Comment by timothycosta** [comment]
I just installed eidelon and took the default iPad Pro 10.5 which took 1:32.  Then iPad Air 2 took 1:34.  So I don't think there's going to be much difference considering we're just using stopwatches.

More important than the simulator might be to specify a commit that everyone should use.  Adding a new framework, etc... could substantially change the build time.

**Comment by ashfurrow** [comment]
That's true, though the project is largely "done" so I don't think we'll be doing anything but the occasional UI tweak.

**Comment by robertjpayne** [comment]
I somewhat wonder if this repo should contain tests that do not include launching the simulator, because launching the simulator "fresh" takes a long time and it invariably makes it harder to measure (you have to use a stop watch).

I'm also thinking a lot of the PR's with build times are not actually reporting time-to-launch simulator but rather just build times.

**Comment by ashfurrow** [comment]
The readme prescribes the clean build to be timed without a simulator open, and an incremental build to be timed with the simulator already open. I chose these two cases because they are extremes, and both common use cases.

It's possible that build times people have added over the years aren't accurate, but that's not really the purpose of this project. For more scientific performance testing, we already have Geekbench, this serves as a sort of relative comparison in terms that affect developers' day-to-day work.
